//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp
{
    using Newtonsoft.Json;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Hooks;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Errors;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils.Retries;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading.Tasks;


    public enum ServerProtocol
    {
        [JsonProperty("https")]
        Https,
    }

    public static class ServerProtocolExtension
    {
        public static string Value(this ServerProtocol value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static ServerProtocol ToEnum(this string value)
        {
            foreach(var field in typeof(ServerProtocol).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is ServerProtocol)
                    {
                        return (ServerProtocol)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum ServerProtocol");
        }
    }

    /// <summary>
    /// Demo API (Scalar Galaxy): The Scalar Galaxy is an example OpenAPI document to test OpenAPI tools and libraries. It&apos;s a fictional universe with fictional planets and fictional data. Get all the data for <a href="#tag/planets/get/planets">all planets</a>.<br/>
    /// 
    /// <remarks>
    /// <br/>
    /// ## Resources<br/>
    /// <br/>
    /// * https://github.com/scalar/scalar<br/>
    /// * https://github.com/OAI/OpenAPI-Specification<br/>
    /// * https://scalar.com<br/>
    /// <br/>
    /// ## Markdown Support<br/>
    /// <br/>
    /// All descriptions *can* contain ~~tons of text~~ **Markdown**. <a href="https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax">If GitHub supports the syntax</a>, chances are we&apos;re supporting it, too. You can even create <a href="#tag/authentication/post/user/signup">internal links to reference endpoints</a>.<br/>
    /// <br/>
    /// &lt;details&gt;<br/>
    ///   &lt;summary&gt;Examples&lt;/summary&gt;<br/>
    /// <br/>
    ///   **Blockquotes**<br/>
    /// <br/>
    ///   &gt; I love OpenAPI. &lt;3<br/>
    /// <br/>
    ///   **Tables**<br/>
    /// <br/>
    ///   | Feature          | Availability |<br/>
    ///   | ---------------- | ------------ |<br/>
    ///   | Markdown Support | ✓            |<br/>
    /// <br/>
    ///   **Accordion**<br/>
    /// <br/>
    ///   ```html<br/>
    ///   &lt;details&gt;<br/>
    ///     &lt;summary&gt;Using Details Tags&lt;/summary&gt;<br/>
    ///     &lt;p&gt;HTML Example&lt;/p&gt;<br/>
    ///   &lt;/details&gt;<br/>
    ///   ```<br/>
    /// <br/>
    ///   **Images**<br/>
    /// <br/>
    ///   Yes, there&apos;s support for images, too!<br/>
    /// <br/>
    ///   !<a href="https://images.placeholders.dev/?width=1280&amp;height=720">Empty placeholder image showing the width/height</a><br/>
    /// <br/>
    ///   **Alerts**<br/>
    /// <br/>
    ///   &gt; [!tip]<br/>
    ///   &gt; You can now use markdown alerts in your descriptions.<br/>
    /// <br/>
    /// &lt;/details&gt;<br/>
    /// 
    /// </remarks>
    /// 
    /// <see>https://github.com/scalar/scalar} - Documentation</see>
    /// </summary>
    public interface IDemoApiScalarGalaxy
    {

        /// <summary>
        /// Everything about planets
        /// </summary>
        public IPlanets Planets { get; }

        /// <summary>
        /// Celestial bodies are the planets and satellites in the Scalar Galaxy.
        /// </summary>
        public ICelestialBodies CelestialBodies { get; }

        /// <summary>
        /// Some endpoints are public, but some require authentication. We provide all the required endpoints to create an account and authorize yourself.
        /// </summary>
        public IAuthentication Authentication { get; }
    }


    /// <summary>
    /// Demo API (Scalar Galaxy): The Scalar Galaxy is an example OpenAPI document to test OpenAPI tools and libraries. It&apos;s a fictional universe with fictional planets and fictional data. Get all the data for <a href="#tag/planets/get/planets">all planets</a>.<br/>
    /// 
    /// <remarks>
    /// <br/>
    /// ## Resources<br/>
    /// <br/>
    /// * https://github.com/scalar/scalar<br/>
    /// * https://github.com/OAI/OpenAPI-Specification<br/>
    /// * https://scalar.com<br/>
    /// <br/>
    /// ## Markdown Support<br/>
    /// <br/>
    /// All descriptions *can* contain ~~tons of text~~ **Markdown**. <a href="https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax">If GitHub supports the syntax</a>, chances are we&apos;re supporting it, too. You can even create <a href="#tag/authentication/post/user/signup">internal links to reference endpoints</a>.<br/>
    /// <br/>
    /// &lt;details&gt;<br/>
    ///   &lt;summary&gt;Examples&lt;/summary&gt;<br/>
    /// <br/>
    ///   **Blockquotes**<br/>
    /// <br/>
    ///   &gt; I love OpenAPI. &lt;3<br/>
    /// <br/>
    ///   **Tables**<br/>
    /// <br/>
    ///   | Feature          | Availability |<br/>
    ///   | ---------------- | ------------ |<br/>
    ///   | Markdown Support | ✓            |<br/>
    /// <br/>
    ///   **Accordion**<br/>
    /// <br/>
    ///   ```html<br/>
    ///   &lt;details&gt;<br/>
    ///     &lt;summary&gt;Using Details Tags&lt;/summary&gt;<br/>
    ///     &lt;p&gt;HTML Example&lt;/p&gt;<br/>
    ///   &lt;/details&gt;<br/>
    ///   ```<br/>
    /// <br/>
    ///   **Images**<br/>
    /// <br/>
    ///   Yes, there&apos;s support for images, too!<br/>
    /// <br/>
    ///   !<a href="https://images.placeholders.dev/?width=1280&amp;height=720">Empty placeholder image showing the width/height</a><br/>
    /// <br/>
    ///   **Alerts**<br/>
    /// <br/>
    ///   &gt; [!tip]<br/>
    ///   &gt; You can now use markdown alerts in your descriptions.<br/>
    /// <br/>
    /// &lt;/details&gt;<br/>
    /// 
    /// </remarks>
    /// 
    /// <see>https://github.com/scalar/scalar} - Documentation</see>
    /// </summary>
    public class DemoApiScalarGalaxy: IDemoApiScalarGalaxy
    {
        public SDKConfig SDKConfiguration { get; private set; }

        private const string _language = "csharp";
        private const string _sdkVersion = "1.0.0";
        private const string _sdkGenVersion = "2.634.2";
        private const string _openapiDocVersion = "1.0.0";
        public IPlanets Planets { get; private set; }
        public ICelestialBodies CelestialBodies { get; private set; }
        public IAuthentication Authentication { get; private set; }

        public DemoApiScalarGalaxy(SDKConfig config)
        {
            SDKConfiguration = config;
            InitHooks();

            Planets = new Planets(SDKConfiguration);

            CelestialBodies = new CelestialBodies(SDKConfiguration);

            Authentication = new Authentication(SDKConfiguration);
        }

        public DemoApiScalarGalaxy(Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components.Security? security = null, Func<Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components.Security>? securitySource = null, int? serverIndex = null, ServerProtocol? protocol = null, string?  path = null, string? serverUrl = null, Dictionary<string, string>? urlParams = null, ISpeakeasyHttpClient? client = null, RetryConfig? retryConfig = null)
        {
            if (serverIndex != null)
            {
                if (serverIndex.Value < 0 || serverIndex.Value >= SDKConfig.ServerList.Length)
                {
                    throw new Exception($"Invalid server index {serverIndex.Value}");
                }
            }

            if (serverUrl != null)
            {
                if (urlParams != null)
                {
                    serverUrl = Utilities.TemplateUrl(serverUrl, urlParams);
                }
            }
            Func<Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components.Security>? _securitySource = null;

            if(securitySource != null)
            {
                _securitySource = securitySource;
            }
            else if(security != null)
            {
                _securitySource = () => security;
            }

            SDKConfiguration = new SDKConfig(client)
            {
                ServerIndex = serverIndex == null ? 0 : serverIndex.Value,
                ServerUrl = serverUrl == null ? "" : serverUrl,
                SecuritySource = _securitySource,
                RetryConfig = retryConfig
            };

            if (protocol != null)
            {
                SDKConfiguration.SetServerVariable("protocol", ServerProtocolExtension.Value(protocol.Value));
            }

            if (path != null)
            {
                SDKConfiguration.SetServerVariable("path", path);
            }

            InitHooks();

            Planets = new Planets(SDKConfiguration);

            CelestialBodies = new CelestialBodies(SDKConfiguration);

            Authentication = new Authentication(SDKConfiguration);
        }

        private void InitHooks()
        {
            SDKConfiguration = SDKConfiguration.Hooks.SDKInit(SDKConfiguration);
        }

        public class SDKBuilder
        {
            private SDKConfig _sdkConfig = new SDKConfig(client: new SpeakeasyHttpClient());

            public SDKBuilder() { }

            public SDKBuilder WithServerIndex(int serverIndex)
            {
                if (serverIndex < 0 || serverIndex >= SDKConfig.ServerList.Length)
                {
                    throw new Exception($"Invalid server index {serverIndex}");
                }
                _sdkConfig.ServerIndex = serverIndex;
                return this;
            }

            public SDKBuilder WithProtocol(ServerProtocol protocol)
            {
                _sdkConfig.SetServerVariable("protocol", ServerProtocolExtension.Value(protocol));
                return this;
            }

            public SDKBuilder WithPath(string path)
            {
                _sdkConfig.SetServerVariable("path", path);
                return this;
            }

            public SDKBuilder WithServerUrl(string serverUrl, Dictionary<string, string>? serverVariables = null)
            {
                if (serverVariables != null)
                {
                    serverUrl = Utilities.TemplateUrl(serverUrl, serverVariables);
                }
                _sdkConfig.ServerUrl = serverUrl;
                return this;
            }

            public SDKBuilder WithSecuritySource(Func<Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components.Security> securitySource)
            {
                _sdkConfig.SecuritySource = securitySource;
                return this;
            }

            public SDKBuilder WithSecurity(Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components.Security security)
            {
                _sdkConfig.SecuritySource = () => security;
                return this;
            }

            public SDKBuilder WithClient(ISpeakeasyHttpClient client)
            {
                _sdkConfig.Client = client;
                return this;
            }

            public SDKBuilder WithRetryConfig(RetryConfig retryConfig)
            {
                _sdkConfig.RetryConfig = retryConfig;
                return this;
            }

            public DemoApiScalarGalaxy Build()
            {
              return new DemoApiScalarGalaxy(_sdkConfig);
            }

        }

        public static SDKBuilder Builder() => new SDKBuilder();
    }
}