//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp
{
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Hooks;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils.Retries;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public struct SDKConfig
    {
        /// <summary>
        /// List of server URLs available to the SDK.
        /// </summary>
        public static readonly string[] ServerList = {
            "https://galaxy.scalar.com",
            "{protocol}://void.scalar.com/{path}",
        };

        public ISpeakeasyHttpClient Client;
        public string ServerUrl;
        public int ServerIndex;
        public List<Dictionary<string, string>> ServerVariables;
        public string UserAgent;
        public Func<Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components.Security>? SecuritySource;
        public SDKHooks Hooks;
        public RetryConfig? RetryConfig;

        /// <summary>
        /// Initializes a new instance of the SDKConfig struct with default values.
        /// </summary>
        public SDKConfig(ISpeakeasyHttpClient? client = null)
        {
            Client = client ?? new SpeakeasyHttpClient();
            ServerUrl = "";
            ServerIndex = 0;
            ServerVariables = new List<Dictionary<string, string>>()
            {
                new Dictionary<string, string>()
                {
                },
                new Dictionary<string, string>()
                {
                    {"protocol", "https"},
                    {"path", ""},
                },
            };
            UserAgent = "speakeasy-sdk/csharp 1.0.0 2.634.2 1.0.0 Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp";
            SecuritySource = null;
            Hooks = new SDKHooks();
            RetryConfig = null;
        }

        public void SetServerVariable(string key, string value)
        {
            foreach (var serverVariables in this.ServerVariables.Where(dict => dict.ContainsKey(key)))
            {
                serverVariables[key] = value;
            }
        }

        public string GetTemplatedServerUrl()
        {
            if (!String.IsNullOrEmpty(this.ServerUrl))
            {
                return Utilities.TemplateUrl(Utilities.RemoveSuffix(this.ServerUrl, "/"), new Dictionary<string, string>());
            }
            return Utilities.TemplateUrl(SDKConfig.ServerList[this.ServerIndex], this.ServerVariables[this.ServerIndex]);
        }
    }
}