/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { celestialBodiesCreateCelestialBody } from "../funcs/celestialBodiesCreateCelestialBody.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class CelestialBodies extends ClientSDK {
  /**
   * Create a celestial body
   */
  async createCelestialBody(
    request: components.CelestialBodyInput,
    options?: RequestOptions,
  ): Promise<components.CelestialBody> {
    return unwrapAsync(celestialBodiesCreateCelestialBody(
      this,
      request,
      options,
    ));
  }
}
