/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Authentication } from "./authentication.js";
import { CelestialBodies } from "./celestialbodies.js";
import { Planets } from "./planets.js";

export class DemoApiScalarGalaxy extends ClientSDK {
  private _planets?: Planets;
  get planets(): Planets {
    return (this._planets ??= new Planets(this._options));
  }

  private _celestialBodies?: CelestialBodies;
  get celestialBodies(): CelestialBodies {
    return (this._celestialBodies ??= new CelestialBodies(this._options));
  }

  private _authentication?: Authentication;
  get authentication(): Authentication {
    return (this._authentication ??= new Authentication(this._options));
  }
}
