//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components
{
    using Newtonsoft.Json;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    using System.Collections.Generic;
    
    public class Atmosphere
    {

        [JsonProperty("compound")]
        public string? Compound { get; set; }

        [JsonProperty("percentage")]
        public float? Percentage { get; set; }

        [JsonProperty("additionalProperties")]
        public Dictionary<string, string>? AdditionalProperties { get; set; }
    }
}