//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class CelestialBodyType
    {
        private CelestialBodyType(string value) { Value = value; }

        public string Value { get; private set; }
        
        public static CelestialBodyType Planet { get { return new CelestialBodyType("planet"); } }
        public static CelestialBodyType Satellite { get { return new CelestialBodyType("satellite"); } }
        public static CelestialBodyType Null { get { return new CelestialBodyType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(CelestialBodyType v) { return v.Value; }
        public static CelestialBodyType FromString(string v) {
            switch(v) {
                case "planet": return Planet;
                case "satellite": return Satellite;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for CelestialBodyType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((CelestialBodyType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// A celestial body which can be either a planet or a satellite
    /// </summary>
    [JsonConverter(typeof(CelestialBody.CelestialBodyConverter))]
    public class CelestialBody {
        public CelestialBody(CelestialBodyType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public Planet? Planet { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public Satellite? Satellite { get; set; }

        public CelestialBodyType Type { get; set; }


        public static CelestialBody CreatePlanet(Planet planet) {
            CelestialBodyType typ = CelestialBodyType.Planet;
        
            string typStr = CelestialBodyType.Planet.ToString();
            
            planet.Type = Models.Components.TypeExtension.ToEnum(CelestialBodyType.Planet.ToString());
            CelestialBody res = new CelestialBody(typ);
            res.Planet = planet;
            return res;
        }
        public static CelestialBody CreateSatellite(Satellite satellite) {
            CelestialBodyType typ = CelestialBodyType.Satellite;
        
            string typStr = CelestialBodyType.Satellite.ToString();
            
            satellite.Type = SatelliteTypeExtension.ToEnum(CelestialBodyType.Satellite.ToString());
            CelestialBody res = new CelestialBody(typ);
            res.Satellite = satellite;
            return res;
        }
        public static CelestialBody CreateNull() {
            CelestialBodyType typ = CelestialBodyType.Null;
            return new CelestialBody(typ);
        }

        public class CelestialBodyConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(CelestialBody);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                JObject jo = JObject.Load(reader);
                string discriminator = jo.GetValue("type")?.ToString() ?? throw new ArgumentNullException("Could not find discriminator field.");
                if (discriminator == CelestialBodyType.Planet.ToString())
                {
                    Planet? planet = ResponseBodyDeserializer.Deserialize<Planet>(jo.ToString());
                    return CreatePlanet(planet!);
                }
                if (discriminator == CelestialBodyType.Satellite.ToString())
                {
                    Satellite? satellite = ResponseBodyDeserializer.Deserialize<Satellite>(jo.ToString());
                    return CreateSatellite(satellite!);
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                CelestialBody res = (CelestialBody)value;
                if (CelestialBodyType.FromString(res.Type).Equals(CelestialBodyType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Planet != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Planet));
                    return;
                }
                if (res.Satellite != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Satellite));
                    return;
                }

            }

        }

    }
}