//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class CelestialBodyInputType
    {
        private CelestialBodyInputType(string value) { Value = value; }

        public string Value { get; private set; }
        
        public static CelestialBodyInputType Planet { get { return new CelestialBodyInputType("planet"); } }
        public static CelestialBodyInputType Satellite { get { return new CelestialBodyInputType("satellite"); } }
        public static CelestialBodyInputType Null { get { return new CelestialBodyInputType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(CelestialBodyInputType v) { return v.Value; }
        public static CelestialBodyInputType FromString(string v) {
            switch(v) {
                case "planet": return Planet;
                case "satellite": return Satellite;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for CelestialBodyInputType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((CelestialBodyInputType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// A celestial body which can be either a planet or a satellite
    /// </summary>
    [JsonConverter(typeof(CelestialBodyInput.CelestialBodyInputConverter))]
    public class CelestialBodyInput {
        public CelestialBodyInput(CelestialBodyInputType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public PlanetInput? PlanetInput { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public SatelliteInput? SatelliteInput { get; set; }

        public CelestialBodyInputType Type { get; set; }


        public static CelestialBodyInput CreatePlanet(PlanetInput planet) {
            CelestialBodyInputType typ = CelestialBodyInputType.Planet;
        
            string typStr = CelestialBodyInputType.Planet.ToString();
            
            planet.Type = Models.Components.TypeExtension.ToEnum(CelestialBodyInputType.Planet.ToString());
            CelestialBodyInput res = new CelestialBodyInput(typ);
            res.PlanetInput = planet;
            return res;
        }
        public static CelestialBodyInput CreateSatellite(SatelliteInput satellite) {
            CelestialBodyInputType typ = CelestialBodyInputType.Satellite;
        
            string typStr = CelestialBodyInputType.Satellite.ToString();
            
            satellite.Type = SatelliteTypeExtension.ToEnum(CelestialBodyInputType.Satellite.ToString());
            CelestialBodyInput res = new CelestialBodyInput(typ);
            res.SatelliteInput = satellite;
            return res;
        }
        public static CelestialBodyInput CreateNull() {
            CelestialBodyInputType typ = CelestialBodyInputType.Null;
            return new CelestialBodyInput(typ);
        }

        public class CelestialBodyInputConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(CelestialBodyInput);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                JObject jo = JObject.Load(reader);
                string discriminator = jo.GetValue("type")?.ToString() ?? throw new ArgumentNullException("Could not find discriminator field.");
                if (discriminator == CelestialBodyInputType.Planet.ToString())
                {
                    PlanetInput? planetInput = ResponseBodyDeserializer.Deserialize<PlanetInput>(jo.ToString());
                    return CreatePlanet(planetInput!);
                }
                if (discriminator == CelestialBodyInputType.Satellite.ToString())
                {
                    SatelliteInput? satelliteInput = ResponseBodyDeserializer.Deserialize<SatelliteInput>(jo.ToString());
                    return CreateSatellite(satelliteInput!);
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                CelestialBodyInput res = (CelestialBodyInput)value;
                if (CelestialBodyInputType.FromString(res.Type).Equals(CelestialBodyInputType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.PlanetInput != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.PlanetInput));
                    return;
                }
                if (res.SatelliteInput != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.SatelliteInput));
                    return;
                }

            }

        }

    }
}