//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components
{
    using Newtonsoft.Json;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    
    /// <summary>
    /// Credentials to authenticate a user
    /// </summary>
    public class Credentials
    {

        [JsonProperty("email")]
        public string Email { get; set; } = default!;

        [JsonProperty("password")]
        public string Password { get; set; } = default!;
    }
}