//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components
{
    using Newtonsoft.Json;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    using System;
    
    /// <summary>
    /// Message about an image upload
    /// </summary>
    public class ImageUploadedMessage
    {

        [JsonProperty("message")]
        public string? Message { get; set; }

        /// <summary>
        /// The URL where the uploaded image can be accessed
        /// </summary>
        [JsonProperty("imageUrl")]
        public string? ImageUrl { get; set; }

        /// <summary>
        /// Timestamp when the image was uploaded
        /// </summary>
        [JsonProperty("uploadedAt")]
        public DateTime? UploadedAt { get; set; }

        /// <summary>
        /// Size of the uploaded image in bytes
        /// </summary>
        [JsonProperty("fileSize")]
        public long? FileSize { get; set; }

        /// <summary>
        /// The content type of the uploaded image
        /// </summary>
        [JsonProperty("mimeType")]
        public string? MimeType { get; set; }
    }
}