//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components
{
    using Newtonsoft.Json;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    
    public class Orbit
    {

        /// <summary>
        /// The ID of the planet this satellite orbits
        /// </summary>
        [JsonProperty("planetId")]
        public long? PlanetId { get; set; }

        /// <summary>
        /// Orbital period in Earth days
        /// </summary>
        [JsonProperty("orbitalPeriod")]
        public float? OrbitalPeriod { get; set; }

        /// <summary>
        /// Average distance from the planet in kilometers
        /// </summary>
        [JsonProperty("distance")]
        public float? Distance { get; set; }
    }
}