//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components
{
    using Newtonsoft.Json;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    using System.Collections.Generic;
    
    public class PhysicalProperties
    {

        /// <summary>
        /// Mass in Earth masses (must be greater than 0)
        /// </summary>
        [JsonProperty("mass")]
        public float? Mass { get; set; }

        /// <summary>
        /// Radius in Earth radii (must be greater than 0)
        /// </summary>
        [JsonProperty("radius")]
        public float? Radius { get; set; }

        /// <summary>
        /// Surface gravity in Earth g
        /// </summary>
        [JsonProperty("gravity")]
        public float? Gravity { get; set; }

        [JsonProperty("temperature")]
        public Temperature? Temperature { get; set; }

        [JsonProperty("additionalProperties")]
        public Dictionary<string, float>? AdditionalProperties { get; set; }
    }
}