//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components
{
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// A planet in the Scalar Galaxy
    /// </summary>
    public class Planet1
    {

        public long Id { get; set; } = default!;

        public string Name { get; set; } = default!;

        public string? Description { get; set; } = null;

        public Models.Components.Type Type { get; set; } = default!;

        /// <summary>
        /// A score from 0 to 1 indicating potential habitability
        /// </summary>
        public float? HabitabilityIndex { get; set; }

        public Dictionary<string, float>? PhysicalProperties { get; set; }

        /// <summary>
        /// Atmospheric composition
        /// </summary>
        public List<Dictionary<string, string>>? Atmosphere { get; set; }

        public DateTime? DiscoveredAt { get; set; }

        public string? Image { get; set; } = null;

        public List<Satellite>? Satellites { get; set; }

        /// <summary>
        /// A user
        /// </summary>
        public User? Creator { get; set; }

        public List<string>? Tags { get; set; }

        public DateTime? LastUpdated { get; set; }

        /// <summary>
        /// URL which gets invoked upon a successful operation
        /// </summary>
        public string? SuccessCallbackUrl { get; set; }

        /// <summary>
        /// URL which gets invoked upon a failed operation
        /// </summary>
        public string? FailureCallbackUrl { get; set; }
    }
}