//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components
{
    using Newtonsoft.Json;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// A planet in the Scalar Galaxy
    /// </summary>
    public class Planet
    {

        [JsonProperty("id")]
        public long Id { get; set; } = default!;

        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        [JsonProperty("description")]
        public string? Description { get; set; } = null;

        [JsonProperty("type")]
        public Models.Components.Type Type { get; set; } = default!;

        /// <summary>
        /// A score from 0 to 1 indicating potential habitability
        /// </summary>
        [JsonProperty("habitabilityIndex")]
        public float? HabitabilityIndex { get; set; }

        [JsonProperty("physicalProperties")]
        public PhysicalProperties? PhysicalProperties { get; set; }

        /// <summary>
        /// Atmospheric composition
        /// </summary>
        [JsonProperty("atmosphere")]
        public List<Atmosphere>? Atmosphere { get; set; }

        [JsonProperty("discoveredAt")]
        public DateTime? DiscoveredAt { get; set; }

        [JsonProperty("image")]
        public string? Image { get; set; } = null;

        [JsonProperty("satellites")]
        public List<Satellite>? Satellites { get; set; }

        /// <summary>
        /// A user
        /// </summary>
        [JsonProperty("creator")]
        public User? Creator { get; set; }

        [JsonProperty("tags")]
        public List<string>? Tags { get; set; }

        [JsonProperty("lastUpdated")]
        public DateTime? LastUpdated { get; set; }

        /// <summary>
        /// URL which gets invoked upon a successful operation
        /// </summary>
        [JsonProperty("successCallbackUrl")]
        public string? SuccessCallbackUrl { get; set; }

        /// <summary>
        /// URL which gets invoked upon a failed operation
        /// </summary>
        [JsonProperty("failureCallbackUrl")]
        public string? FailureCallbackUrl { get; set; }
    }
}