//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components
{
    using Newtonsoft.Json;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    
    /// <summary>
    /// Every satellite in the Scalar Galaxy
    /// </summary>
    public class Satellite
    {

        [JsonProperty("id")]
        public long? Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        [JsonProperty("description")]
        public string? Description { get; set; } = null;

        /// <summary>
        /// Diameter in kilometers
        /// </summary>
        [JsonProperty("diameter")]
        public float? Diameter { get; set; }

        [JsonProperty("type")]
        public SatelliteType Type { get; set; } = default!;

        [JsonProperty("orbit")]
        public Orbit? Orbit { get; set; }
    }
}