//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components
{
    using Newtonsoft.Json;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    using System;
    
    public enum SatelliteType
    {
        [JsonProperty("satellite")]
        Satellite,
        [JsonProperty("moon")]
        Moon,
        [JsonProperty("asteroid")]
        Asteroid,
        [JsonProperty("comet")]
        Comet,
    }

    public static class SatelliteTypeExtension
    {
        public static string Value(this SatelliteType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static SatelliteType ToEnum(this string value)
        {
            foreach(var field in typeof(SatelliteType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is SatelliteType)
                    {
                        return (SatelliteType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum SatelliteType");
        }
    }

}