//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components
{
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    
    public class SchemeOAuth2
    {

        [SpeakeasyMetadata("security:name=clientID")]
        public string ClientID { get; set; } = default!;

        [SpeakeasyMetadata("security:name=clientSecret")]
        public string ClientSecret { get; set; } = default!;

        public string TokenURL { get; set; } = "https://galaxy.scalar.com/oauth/token";
    }
}