//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components
{
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    
    public class Security
    {

        [SpeakeasyMetadata("security:scheme=true,type=http,subType=bearer,name=Authorization")]
        public string? BearerAuth { get; set; }

        [SpeakeasyMetadata("security:scheme=true,type=http,subType=basic")]
        public SchemeBasicAuth? BasicAuth { get; set; }

        [SpeakeasyMetadata("security:scheme=true,type=apiKey,subType=query,name=api_key")]
        public string? ApiKeyQuery { get; set; }

        [SpeakeasyMetadata("security:scheme=true,type=apiKey,subType=header,name=X-API-Key")]
        public string? ApiKeyHeader { get; set; }

        [SpeakeasyMetadata("security:scheme=true,type=apiKey,subType=cookie,name=api_key")]
        public string? ApiKeyCookie { get; set; }

        [SpeakeasyMetadata("security:scheme=true,type=oauth2,subType=client_credentials")]
        public SchemeOAuth2? OAuth2 { get; set; }

        [SpeakeasyMetadata("security:scheme=true,type=openIdConnect,name=Authorization")]
        public string? OpenIdConnect { get; set; }
    }
}