//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components
{
    using Newtonsoft.Json;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    using System.Collections.Generic;
    
    public class Temperature
    {

        /// <summary>
        /// Minimum temperature in Kelvin
        /// </summary>
        [JsonProperty("min")]
        public float? Min { get; set; }

        /// <summary>
        /// Maximum temperature in Kelvin
        /// </summary>
        [JsonProperty("max")]
        public float? Max { get; set; }

        /// <summary>
        /// Average temperature in Kelvin
        /// </summary>
        [JsonProperty("average")]
        public float? Average { get; set; }

        [JsonProperty("additionalProperties")]
        public Dictionary<string, float>? AdditionalProperties { get; set; }
    }
}