//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components
{
    using Newtonsoft.Json;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    
    /// <summary>
    /// A token to authenticate a user
    /// </summary>
    public class Token
    {

        [JsonProperty("token")]
        public string? TokenValue { get; set; }
    }
}