//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Requests
{
    using Newtonsoft.Json;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    
    public class CreateCelestialBodyResponse
    {

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        /// <summary>
        /// Celestial body created
        /// </summary>
        public CelestialBody? CelestialBody { get; set; }

        public Planet? GetCelestialBodyPlanet()
        {
            return CelestialBody != null ? CelestialBody.Planet : null;
        }

        public Satellite? GetCelestialBodySatellite()
        {
            return CelestialBody != null ? CelestialBody.Satellite : null;
        }
    }
}