//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Requests
{
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    
    public class GetAllDataMeta
    {

        public long? Limit { get; set; }

        public long? Offset { get; set; }

        public long? Total { get; set; }

        public string? Next { get; set; } = null;
    }
}