//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Requests
{
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    
    public class UpdatePlanetRawRequest
    {

        /// <summary>
        /// The ID of the planet to get
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=planetId")]
        public long PlanetId { get; set; } = default!;

        /// <summary>
        /// New information about the planet
        /// </summary>
        [SpeakeasyMetadata("request:mediaType=application/xml")]
        public byte[]? Planet { get; set; }
    }
}