//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Requests
{
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Requests;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    
    /// <summary>
    /// Image to upload
    /// </summary>
    public class UploadImageRequestBody
    {

        /// <summary>
        /// The image file to upload
        /// </summary>
        [SpeakeasyMetadata("multipartForm:file,name=image")]
        public Image? Image { get; set; }
    }
}