//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Callbacks
{
    using Newtonsoft.Json;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Models.Components;
    using Perianayaguyjayaselan.DemoApiScalarGalaxyCsharp.Utils;
    
    public class CreatePlanetPlanetCreatedResponse
    {

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;
    }
}