/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PlanetInput,
  PlanetInput$inboundSchema,
  PlanetInput$Outbound,
  PlanetInput$outboundSchema,
} from "./planet.js";
import {
  SatelliteInput,
  SatelliteInput$inboundSchema,
  SatelliteInput$Outbound,
  SatelliteInput$outboundSchema,
} from "./satellite.js";

/**
 * A celestial body which can be either a planet or a satellite
 */
export type CelestialBodyInput =
  | (PlanetInput & { type: "planet" })
  | (SatelliteInput & { type: "satellite" });

/** @internal */
export const CelestialBodyInput$inboundSchema: z.ZodType<
  CelestialBodyInput,
  z.ZodTypeDef,
  unknown
> = z.union([
  PlanetInput$inboundSchema.and(
    z.object({ type: z.literal("planet") }).transform((v) => ({
      type: v.type,
    })),
  ),
  SatelliteInput$inboundSchema.and(
    z.object({ type: z.literal("satellite") }).transform((v) => ({
      type: v.type,
    })),
  ),
]);

/** @internal */
export type CelestialBodyInput$Outbound =
  | (PlanetInput$Outbound & { type: "planet" })
  | (SatelliteInput$Outbound & { type: "satellite" });

/** @internal */
export const CelestialBodyInput$outboundSchema: z.ZodType<
  CelestialBodyInput$Outbound,
  z.ZodTypeDef,
  CelestialBodyInput
> = z.union([
  PlanetInput$outboundSchema.and(
    z.object({ type: z.literal("planet") }).transform((v) => ({
      type: v.type,
    })),
  ),
  SatelliteInput$outboundSchema.and(
    z.object({ type: z.literal("satellite") }).transform((v) => ({
      type: v.type,
    })),
  ),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CelestialBodyInput$ {
  /** @deprecated use `CelestialBodyInput$inboundSchema` instead. */
  export const inboundSchema = CelestialBodyInput$inboundSchema;
  /** @deprecated use `CelestialBodyInput$outboundSchema` instead. */
  export const outboundSchema = CelestialBodyInput$outboundSchema;
  /** @deprecated use `CelestialBodyInput$Outbound` instead. */
  export type Outbound = CelestialBodyInput$Outbound;
}

export function celestialBodyInputToJSON(
  celestialBodyInput: CelestialBodyInput,
): string {
  return JSON.stringify(
    CelestialBodyInput$outboundSchema.parse(celestialBodyInput),
  );
}

export function celestialBodyInputFromJSON(
  jsonString: string,
): SafeParseResult<CelestialBodyInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CelestialBodyInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CelestialBodyInput' from JSON`,
  );
}
