/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Planet,
  Planet$inboundSchema,
  Planet$Outbound,
  Planet$outboundSchema,
} from "./planet.js";
import {
  Satellite,
  Satellite$inboundSchema,
  Satellite$Outbound,
  Satellite$outboundSchema,
} from "./satellite.js";

/**
 * A celestial body which can be either a planet or a satellite
 */
export type CelestialBody =
  | (Planet & { type: "planet" })
  | (Satellite & { type: "satellite" });

/** @internal */
export const CelestialBody$inboundSchema: z.ZodType<
  CelestialBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  Planet$inboundSchema.and(
    z.object({ type: z.literal("planet") }).transform((v) => ({
      type: v.type,
    })),
  ),
  Satellite$inboundSchema.and(
    z.object({ type: z.literal("satellite") }).transform((v) => ({
      type: v.type,
    })),
  ),
]);

/** @internal */
export type CelestialBody$Outbound =
  | (Planet$Outbound & { type: "planet" })
  | (Satellite$Outbound & { type: "satellite" });

/** @internal */
export const CelestialBody$outboundSchema: z.ZodType<
  CelestialBody$Outbound,
  z.ZodTypeDef,
  CelestialBody
> = z.union([
  Planet$outboundSchema.and(
    z.object({ type: z.literal("planet") }).transform((v) => ({
      type: v.type,
    })),
  ),
  Satellite$outboundSchema.and(
    z.object({ type: z.literal("satellite") }).transform((v) => ({
      type: v.type,
    })),
  ),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CelestialBody$ {
  /** @deprecated use `CelestialBody$inboundSchema` instead. */
  export const inboundSchema = CelestialBody$inboundSchema;
  /** @deprecated use `CelestialBody$outboundSchema` instead. */
  export const outboundSchema = CelestialBody$outboundSchema;
  /** @deprecated use `CelestialBody$Outbound` instead. */
  export type Outbound = CelestialBody$Outbound;
}

export function celestialBodyToJSON(celestialBody: CelestialBody): string {
  return JSON.stringify(CelestialBody$outboundSchema.parse(celestialBody));
}

export function celestialBodyFromJSON(
  jsonString: string,
): SafeParseResult<CelestialBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CelestialBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CelestialBody' from JSON`,
  );
}
