/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const SatelliteType = {
  Satellite: "satellite",
  Moon: "moon",
  Asteroid: "asteroid",
  Comet: "comet",
} as const;
export type SatelliteType = ClosedEnum<typeof SatelliteType>;

export type Orbit = {
  /**
   * The ID of the planet this satellite orbits
   */
  planetId?: number | undefined;
  /**
   * Orbital period in Earth days
   */
  orbitalPeriod?: number | undefined;
  /**
   * Average distance from the planet in kilometers
   */
  distance?: number | undefined;
};

/**
 * Every satellite in the Scalar Galaxy
 */
export type Satellite = {
  id?: number | undefined;
  name: string;
  description?: string | null | undefined;
  /**
   * Diameter in kilometers
   */
  diameter?: number | undefined;
  type: SatelliteType;
  orbit?: Orbit | undefined;
};

/**
 * Every satellite in the Scalar Galaxy
 */
export type SatelliteInput = {
  name: string;
  description?: string | null | undefined;
  /**
   * Diameter in kilometers
   */
  diameter?: number | undefined;
  type: SatelliteType;
  orbit?: Orbit | undefined;
};

/** @internal */
export const SatelliteType$inboundSchema: z.ZodNativeEnum<
  typeof SatelliteType
> = z.nativeEnum(SatelliteType);

/** @internal */
export const SatelliteType$outboundSchema: z.ZodNativeEnum<
  typeof SatelliteType
> = SatelliteType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SatelliteType$ {
  /** @deprecated use `SatelliteType$inboundSchema` instead. */
  export const inboundSchema = SatelliteType$inboundSchema;
  /** @deprecated use `SatelliteType$outboundSchema` instead. */
  export const outboundSchema = SatelliteType$outboundSchema;
}

/** @internal */
export const Orbit$inboundSchema: z.ZodType<Orbit, z.ZodTypeDef, unknown> = z
  .object({
    planetId: z.number().int().optional(),
    orbitalPeriod: z.number().optional(),
    distance: z.number().optional(),
  });

/** @internal */
export type Orbit$Outbound = {
  planetId?: number | undefined;
  orbitalPeriod?: number | undefined;
  distance?: number | undefined;
};

/** @internal */
export const Orbit$outboundSchema: z.ZodType<
  Orbit$Outbound,
  z.ZodTypeDef,
  Orbit
> = z.object({
  planetId: z.number().int().optional(),
  orbitalPeriod: z.number().optional(),
  distance: z.number().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Orbit$ {
  /** @deprecated use `Orbit$inboundSchema` instead. */
  export const inboundSchema = Orbit$inboundSchema;
  /** @deprecated use `Orbit$outboundSchema` instead. */
  export const outboundSchema = Orbit$outboundSchema;
  /** @deprecated use `Orbit$Outbound` instead. */
  export type Outbound = Orbit$Outbound;
}

export function orbitToJSON(orbit: Orbit): string {
  return JSON.stringify(Orbit$outboundSchema.parse(orbit));
}

export function orbitFromJSON(
  jsonString: string,
): SafeParseResult<Orbit, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Orbit$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Orbit' from JSON`,
  );
}

/** @internal */
export const Satellite$inboundSchema: z.ZodType<
  Satellite,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int().optional(),
  name: z.string(),
  description: z.nullable(z.string()).optional(),
  diameter: z.number().optional(),
  type: SatelliteType$inboundSchema,
  orbit: z.lazy(() => Orbit$inboundSchema).optional(),
});

/** @internal */
export type Satellite$Outbound = {
  id?: number | undefined;
  name: string;
  description?: string | null | undefined;
  diameter?: number | undefined;
  type: string;
  orbit?: Orbit$Outbound | undefined;
};

/** @internal */
export const Satellite$outboundSchema: z.ZodType<
  Satellite$Outbound,
  z.ZodTypeDef,
  Satellite
> = z.object({
  id: z.number().int().optional(),
  name: z.string(),
  description: z.nullable(z.string()).optional(),
  diameter: z.number().optional(),
  type: SatelliteType$outboundSchema,
  orbit: z.lazy(() => Orbit$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Satellite$ {
  /** @deprecated use `Satellite$inboundSchema` instead. */
  export const inboundSchema = Satellite$inboundSchema;
  /** @deprecated use `Satellite$outboundSchema` instead. */
  export const outboundSchema = Satellite$outboundSchema;
  /** @deprecated use `Satellite$Outbound` instead. */
  export type Outbound = Satellite$Outbound;
}

export function satelliteToJSON(satellite: Satellite): string {
  return JSON.stringify(Satellite$outboundSchema.parse(satellite));
}

export function satelliteFromJSON(
  jsonString: string,
): SafeParseResult<Satellite, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Satellite$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Satellite' from JSON`,
  );
}

/** @internal */
export const SatelliteInput$inboundSchema: z.ZodType<
  SatelliteInput,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  description: z.nullable(z.string()).optional(),
  diameter: z.number().optional(),
  type: SatelliteType$inboundSchema,
  orbit: z.lazy(() => Orbit$inboundSchema).optional(),
});

/** @internal */
export type SatelliteInput$Outbound = {
  name: string;
  description?: string | null | undefined;
  diameter?: number | undefined;
  type: string;
  orbit?: Orbit$Outbound | undefined;
};

/** @internal */
export const SatelliteInput$outboundSchema: z.ZodType<
  SatelliteInput$Outbound,
  z.ZodTypeDef,
  SatelliteInput
> = z.object({
  name: z.string(),
  description: z.nullable(z.string()).optional(),
  diameter: z.number().optional(),
  type: SatelliteType$outboundSchema,
  orbit: z.lazy(() => Orbit$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SatelliteInput$ {
  /** @deprecated use `SatelliteInput$inboundSchema` instead. */
  export const inboundSchema = SatelliteInput$inboundSchema;
  /** @deprecated use `SatelliteInput$outboundSchema` instead. */
  export const outboundSchema = SatelliteInput$outboundSchema;
  /** @deprecated use `SatelliteInput$Outbound` instead. */
  export type Outbound = SatelliteInput$Outbound;
}

export function satelliteInputToJSON(satelliteInput: SatelliteInput): string {
  return JSON.stringify(SatelliteInput$outboundSchema.parse(satelliteInput));
}

export function satelliteInputFromJSON(
  jsonString: string,
): SafeParseResult<SatelliteInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SatelliteInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SatelliteInput' from JSON`,
  );
}
