"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .httpclient import AsyncHttpClient, ClientOwner, HttpClient, close_clients
from .sdkconfiguration import SDKConfiguration, ServerProtocol
from .utils.logger import Logger, get_default_logger
from .utils.retries import RetryConfig
import httpx
import importlib
from perianayaguyjayaselan_demo_api_scalar_galaxy_python import models, utils
from perianayaguyjayaselan_demo_api_scalar_galaxy_python._hooks import SDKHooks
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.types import (
    OptionalNullable,
    UNSET,
)
from typing import Callable, Dict, List, Optional, TYPE_CHECKING, Union, cast
import weakref

if TYPE_CHECKING:
    from perianayaguyjayaselan_demo_api_scalar_galaxy_python.authentication import (
        Authentication,
    )
    from perianayaguyjayaselan_demo_api_scalar_galaxy_python.celestial_bodies import (
        CelestialBodies,
    )
    from perianayaguyjayaselan_demo_api_scalar_galaxy_python.planets import Planets


class DemoAPIScalarGalaxy(BaseSDK):
    r"""Demo API (Scalar Galaxy): The Scalar Galaxy is an example OpenAPI document to test OpenAPI tools and libraries. It's a fictional universe with fictional planets and fictional data. Get all the data for [all planets](#tag/planets/get/planets).

    ## Resources

    * https://github.com/scalar/scalar
    * https://github.com/OAI/OpenAPI-Specification
    * https://scalar.com

    ## Markdown Support

    All descriptions *can* contain ~~tons of text~~ **Markdown**. [If GitHub supports the syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax), chances are we're supporting it, too. You can even create [internal links to reference endpoints](#tag/authentication/post/user/signup).

    <details>
    <summary>Examples</summary>

    **Blockquotes**

    > I love OpenAPI. <3

    **Tables**

    | Feature          | Availability |
    | ---------------- | ------------ |
    | Markdown Support | ✓            |

    **Accordion**

    ```html
    <details>
    <summary>Using Details Tags</summary>
    <p>HTML Example</p>
    </details>
    ```

    **Images**

    Yes, there's support for images, too!

    ![Empty placeholder image showing the width/height](https://images.placeholders.dev/?width=1280&height=720)

    **Alerts**

    > [!tip]
    > You can now use markdown alerts in your descriptions.

    </details>

    https://github.com/scalar/scalar - Documentation
    """

    planets: "Planets"
    r"""Everything about planets"""
    celestial_bodies: "CelestialBodies"
    r"""Celestial bodies are the planets and satellites in the Scalar Galaxy."""
    authentication: "Authentication"
    r"""Some endpoints are public, but some require authentication. We provide all the required endpoints to create an account and authorize yourself."""
    _sub_sdk_map = {
        "planets": (
            "perianayaguyjayaselan_demo_api_scalar_galaxy_python.planets",
            "Planets",
        ),
        "celestial_bodies": (
            "perianayaguyjayaselan_demo_api_scalar_galaxy_python.celestial_bodies",
            "CelestialBodies",
        ),
        "authentication": (
            "perianayaguyjayaselan_demo_api_scalar_galaxy_python.authentication",
            "Authentication",
        ),
    }

    def __init__(
        self,
        security: Optional[
            Union[models.Security, Callable[[], models.Security]]
        ] = None,
        protocol: Optional[ServerProtocol] = None,
        path: Optional[str] = None,
        server_idx: Optional[int] = None,
        server_url: Optional[str] = None,
        url_params: Optional[Dict[str, str]] = None,
        client: Optional[HttpClient] = None,
        async_client: Optional[AsyncHttpClient] = None,
        retry_config: OptionalNullable[RetryConfig] = UNSET,
        timeout_ms: Optional[int] = None,
        debug_logger: Optional[Logger] = None,
    ) -> None:
        r"""Instantiates the SDK configuring it with the provided parameters.

        :param security: The security details required for authentication
        :param protocol: Allows setting the protocol variable for url substitution
        :param path: Allows setting the path variable for url substitution
        :param server_idx: The index of the server to use for all methods
        :param server_url: The server URL to use for all methods
        :param url_params: Parameters to optionally template the server URL with
        :param client: The HTTP client to use for all synchronous methods
        :param async_client: The Async HTTP client to use for all asynchronous methods
        :param retry_config: The retry configuration to use for all supported methods
        :param timeout_ms: Optional request timeout applied to each operation in milliseconds
        """
        client_supplied = True
        if client is None:
            client = httpx.Client()
            client_supplied = False

        assert issubclass(
            type(client), HttpClient
        ), "The provided client must implement the HttpClient protocol."

        async_client_supplied = True
        if async_client is None:
            async_client = httpx.AsyncClient()
            async_client_supplied = False

        if debug_logger is None:
            debug_logger = get_default_logger()

        assert issubclass(
            type(async_client), AsyncHttpClient
        ), "The provided async_client must implement the AsyncHttpClient protocol."

        if server_url is not None:
            if url_params is not None:
                server_url = utils.template_url(server_url, url_params)
        server_defaults: List[Dict[str, str]] = [
            {},
            {
                "protocol": protocol or "https",
                "path": path or "",
            },
        ]

        BaseSDK.__init__(
            self,
            SDKConfiguration(
                client=client,
                client_supplied=client_supplied,
                async_client=async_client,
                async_client_supplied=async_client_supplied,
                security=security,
                server_url=server_url,
                server_idx=server_idx,
                server_defaults=server_defaults,
                retry_config=retry_config,
                timeout_ms=timeout_ms,
                debug_logger=debug_logger,
            ),
        )

        hooks = SDKHooks()

        # pylint: disable=protected-access
        self.sdk_configuration.__dict__["_hooks"] = hooks

        self.sdk_configuration = hooks.sdk_init(self.sdk_configuration)

        weakref.finalize(
            self,
            close_clients,
            cast(ClientOwner, self.sdk_configuration),
            self.sdk_configuration.client,
            self.sdk_configuration.client_supplied,
            self.sdk_configuration.async_client,
            self.sdk_configuration.async_client_supplied,
        )

    def __getattr__(self, name: str):
        if name in self._sub_sdk_map:
            module_path, class_name = self._sub_sdk_map[name]
            try:
                module = importlib.import_module(module_path)
                klass = getattr(module, class_name)
                instance = klass(self.sdk_configuration)
                setattr(self, name, instance)
                return instance
            except ImportError as e:
                raise AttributeError(
                    f"Failed to import module {module_path} for attribute {name}: {e}"
                ) from e
            except AttributeError as e:
                raise AttributeError(
                    f"Failed to find class {class_name} in module {module_path} for attribute {name}: {e}"
                ) from e

        raise AttributeError(
            f"'{type(self).__name__}' object has no attribute '{name}'"
        )

    def __dir__(self):
        default_attrs = list(super().__dir__())
        lazy_attrs = list(self._sub_sdk_map.keys())
        return sorted(list(set(default_attrs + lazy_attrs)))

    def __enter__(self):
        return self

    async def __aenter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.client is not None
            and not self.sdk_configuration.client_supplied
        ):
            self.sdk_configuration.client.close()
        self.sdk_configuration.client = None

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.async_client is not None
            and not self.sdk_configuration.async_client_supplied
        ):
            await self.sdk_configuration.async_client.aclose()
        self.sdk_configuration.async_client = None
