"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module

if TYPE_CHECKING:
    from .apierror import APIError
    from .celestialbody import CelestialBody, CelestialBodyTypedDict
    from .celestialbody_input import CelestialBodyInput, CelestialBodyInputTypedDict
    from .createplanet_jsonop import (
        CreatePlanetJSONResponse,
        CreatePlanetJSONResponseTypedDict,
    )
    from .createplanet_rawop import (
        CreatePlanetRawResponse,
        CreatePlanetRawResponseTypedDict,
    )
    from .createuser_jsonop import (
        CreateUserJSONRequestBody,
        CreateUserJSONRequestBodyTypedDict,
        CreateUserJSONResponse,
        CreateUserJSONResponseTypedDict,
    )
    from .createuser_rawop import CreateUserRawResponse, CreateUserRawResponseTypedDict
    from .credentials import Credentials, CredentialsTypedDict
    from .deleteplanetop import DeletePlanetRequest, DeletePlanetRequestTypedDict
    from .getalldataop import (
        GetAllDataMeta,
        GetAllDataMetaTypedDict,
        GetAllDataPlanetsResponseBody,
        GetAllDataPlanetsResponseBodyTypedDict,
        GetAllDataRequest,
        GetAllDataRequestTypedDict,
        GetAllDataResponse,
        GetAllDataResponseBody,
        GetAllDataResponseBodyTypedDict,
        GetAllDataResponseTypedDict,
        Meta,
        MetaTypedDict,
    )
    from .getmeop import GetMeResponse, GetMeResponseTypedDict
    from .getplanetop import (
        GetPlanetRequest,
        GetPlanetRequestTypedDict,
        GetPlanetResponse,
        GetPlanetResponseTypedDict,
    )
    from .gettoken_jsonop import GetTokenJSONResponse, GetTokenJSONResponseTypedDict
    from .gettoken_rawop import GetTokenRawResponse, GetTokenRawResponseTypedDict
    from .imageuploadedmessage import (
        ImageUploadedMessage,
        ImageUploadedMessageTypedDict,
    )
    from .planet import (
        Atmosphere,
        AtmosphereTypedDict,
        PhysicalProperties,
        PhysicalPropertiesTypedDict,
        Planet,
        Planet1,
        Planet1TypedDict,
        PlanetInput,
        PlanetInputTypedDict,
        PlanetTypedDict,
        Temperature,
        TemperatureTypedDict,
        Type,
    )
    from .satellite import (
        Orbit,
        OrbitTypedDict,
        Satellite,
        SatelliteInput,
        SatelliteInputTypedDict,
        SatelliteType,
        SatelliteTypedDict,
    )
    from .schemebasicauth import SchemeBasicAuth, SchemeBasicAuthTypedDict
    from .schemeoauth2 import SchemeOAuth2, SchemeOAuth2TypedDict
    from .security import Security, SecurityTypedDict
    from .token import Token, TokenTypedDict
    from .updateplanet_jsonop import (
        UpdatePlanetJSONRequest,
        UpdatePlanetJSONRequestTypedDict,
        UpdatePlanetJSONResponse,
        UpdatePlanetJSONResponseTypedDict,
    )
    from .updateplanet_rawop import (
        UpdatePlanetRawRequest,
        UpdatePlanetRawRequestTypedDict,
        UpdatePlanetRawResponse,
        UpdatePlanetRawResponseTypedDict,
    )
    from .uploadimageop import (
        Image,
        ImageTypedDict,
        UploadImageRequest,
        UploadImageRequestBody,
        UploadImageRequestBodyTypedDict,
        UploadImageRequestTypedDict,
        UploadImageResponse,
        UploadImageResponseTypedDict,
    )
    from .user import User, UserTypedDict
    from .user_input import UserInput, UserInputTypedDict

__all__ = [
    "APIError",
    "Atmosphere",
    "AtmosphereTypedDict",
    "CelestialBody",
    "CelestialBodyInput",
    "CelestialBodyInputTypedDict",
    "CelestialBodyTypedDict",
    "CreatePlanetJSONResponse",
    "CreatePlanetJSONResponseTypedDict",
    "CreatePlanetRawResponse",
    "CreatePlanetRawResponseTypedDict",
    "CreateUserJSONRequestBody",
    "CreateUserJSONRequestBodyTypedDict",
    "CreateUserJSONResponse",
    "CreateUserJSONResponseTypedDict",
    "CreateUserRawResponse",
    "CreateUserRawResponseTypedDict",
    "Credentials",
    "CredentialsTypedDict",
    "DeletePlanetRequest",
    "DeletePlanetRequestTypedDict",
    "GetAllDataMeta",
    "GetAllDataMetaTypedDict",
    "GetAllDataPlanetsResponseBody",
    "GetAllDataPlanetsResponseBodyTypedDict",
    "GetAllDataRequest",
    "GetAllDataRequestTypedDict",
    "GetAllDataResponse",
    "GetAllDataResponseBody",
    "GetAllDataResponseBodyTypedDict",
    "GetAllDataResponseTypedDict",
    "GetMeResponse",
    "GetMeResponseTypedDict",
    "GetPlanetRequest",
    "GetPlanetRequestTypedDict",
    "GetPlanetResponse",
    "GetPlanetResponseTypedDict",
    "GetTokenJSONResponse",
    "GetTokenJSONResponseTypedDict",
    "GetTokenRawResponse",
    "GetTokenRawResponseTypedDict",
    "Image",
    "ImageTypedDict",
    "ImageUploadedMessage",
    "ImageUploadedMessageTypedDict",
    "Meta",
    "MetaTypedDict",
    "Orbit",
    "OrbitTypedDict",
    "PhysicalProperties",
    "PhysicalPropertiesTypedDict",
    "Planet",
    "Planet1",
    "Planet1TypedDict",
    "PlanetInput",
    "PlanetInputTypedDict",
    "PlanetTypedDict",
    "Satellite",
    "SatelliteInput",
    "SatelliteInputTypedDict",
    "SatelliteType",
    "SatelliteTypedDict",
    "SchemeBasicAuth",
    "SchemeBasicAuthTypedDict",
    "SchemeOAuth2",
    "SchemeOAuth2TypedDict",
    "Security",
    "SecurityTypedDict",
    "Temperature",
    "TemperatureTypedDict",
    "Token",
    "TokenTypedDict",
    "Type",
    "UpdatePlanetJSONRequest",
    "UpdatePlanetJSONRequestTypedDict",
    "UpdatePlanetJSONResponse",
    "UpdatePlanetJSONResponseTypedDict",
    "UpdatePlanetRawRequest",
    "UpdatePlanetRawRequestTypedDict",
    "UpdatePlanetRawResponse",
    "UpdatePlanetRawResponseTypedDict",
    "UploadImageRequest",
    "UploadImageRequestBody",
    "UploadImageRequestBodyTypedDict",
    "UploadImageRequestTypedDict",
    "UploadImageResponse",
    "UploadImageResponseTypedDict",
    "User",
    "UserInput",
    "UserInputTypedDict",
    "UserTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "APIError": ".apierror",
    "CelestialBody": ".celestialbody",
    "CelestialBodyTypedDict": ".celestialbody",
    "CelestialBodyInput": ".celestialbody_input",
    "CelestialBodyInputTypedDict": ".celestialbody_input",
    "CreatePlanetJSONResponse": ".createplanet_jsonop",
    "CreatePlanetJSONResponseTypedDict": ".createplanet_jsonop",
    "CreatePlanetRawResponse": ".createplanet_rawop",
    "CreatePlanetRawResponseTypedDict": ".createplanet_rawop",
    "CreateUserJSONRequestBody": ".createuser_jsonop",
    "CreateUserJSONRequestBodyTypedDict": ".createuser_jsonop",
    "CreateUserJSONResponse": ".createuser_jsonop",
    "CreateUserJSONResponseTypedDict": ".createuser_jsonop",
    "CreateUserRawResponse": ".createuser_rawop",
    "CreateUserRawResponseTypedDict": ".createuser_rawop",
    "Credentials": ".credentials",
    "CredentialsTypedDict": ".credentials",
    "DeletePlanetRequest": ".deleteplanetop",
    "DeletePlanetRequestTypedDict": ".deleteplanetop",
    "GetAllDataMeta": ".getalldataop",
    "GetAllDataMetaTypedDict": ".getalldataop",
    "GetAllDataPlanetsResponseBody": ".getalldataop",
    "GetAllDataPlanetsResponseBodyTypedDict": ".getalldataop",
    "GetAllDataRequest": ".getalldataop",
    "GetAllDataRequestTypedDict": ".getalldataop",
    "GetAllDataResponse": ".getalldataop",
    "GetAllDataResponseBody": ".getalldataop",
    "GetAllDataResponseBodyTypedDict": ".getalldataop",
    "GetAllDataResponseTypedDict": ".getalldataop",
    "Meta": ".getalldataop",
    "MetaTypedDict": ".getalldataop",
    "GetMeResponse": ".getmeop",
    "GetMeResponseTypedDict": ".getmeop",
    "GetPlanetRequest": ".getplanetop",
    "GetPlanetRequestTypedDict": ".getplanetop",
    "GetPlanetResponse": ".getplanetop",
    "GetPlanetResponseTypedDict": ".getplanetop",
    "GetTokenJSONResponse": ".gettoken_jsonop",
    "GetTokenJSONResponseTypedDict": ".gettoken_jsonop",
    "GetTokenRawResponse": ".gettoken_rawop",
    "GetTokenRawResponseTypedDict": ".gettoken_rawop",
    "ImageUploadedMessage": ".imageuploadedmessage",
    "ImageUploadedMessageTypedDict": ".imageuploadedmessage",
    "Atmosphere": ".planet",
    "AtmosphereTypedDict": ".planet",
    "PhysicalProperties": ".planet",
    "PhysicalPropertiesTypedDict": ".planet",
    "Planet": ".planet",
    "Planet1": ".planet",
    "Planet1TypedDict": ".planet",
    "PlanetInput": ".planet",
    "PlanetInputTypedDict": ".planet",
    "PlanetTypedDict": ".planet",
    "Temperature": ".planet",
    "TemperatureTypedDict": ".planet",
    "Type": ".planet",
    "Orbit": ".satellite",
    "OrbitTypedDict": ".satellite",
    "Satellite": ".satellite",
    "SatelliteInput": ".satellite",
    "SatelliteInputTypedDict": ".satellite",
    "SatelliteType": ".satellite",
    "SatelliteTypedDict": ".satellite",
    "SchemeBasicAuth": ".schemebasicauth",
    "SchemeBasicAuthTypedDict": ".schemebasicauth",
    "SchemeOAuth2": ".schemeoauth2",
    "SchemeOAuth2TypedDict": ".schemeoauth2",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "Token": ".token",
    "TokenTypedDict": ".token",
    "UpdatePlanetJSONRequest": ".updateplanet_jsonop",
    "UpdatePlanetJSONRequestTypedDict": ".updateplanet_jsonop",
    "UpdatePlanetJSONResponse": ".updateplanet_jsonop",
    "UpdatePlanetJSONResponseTypedDict": ".updateplanet_jsonop",
    "UpdatePlanetRawRequest": ".updateplanet_rawop",
    "UpdatePlanetRawRequestTypedDict": ".updateplanet_rawop",
    "UpdatePlanetRawResponse": ".updateplanet_rawop",
    "UpdatePlanetRawResponseTypedDict": ".updateplanet_rawop",
    "Image": ".uploadimageop",
    "ImageTypedDict": ".uploadimageop",
    "UploadImageRequest": ".uploadimageop",
    "UploadImageRequestBody": ".uploadimageop",
    "UploadImageRequestBodyTypedDict": ".uploadimageop",
    "UploadImageRequestTypedDict": ".uploadimageop",
    "UploadImageResponse": ".uploadimageop",
    "UploadImageResponseTypedDict": ".uploadimageop",
    "User": ".user",
    "UserTypedDict": ".user",
    "UserInput": ".user_input",
    "UserInputTypedDict": ".user_input",
}


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = import_module(module_name, __package__)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)
