"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .planet import PlanetInput, PlanetInputTypedDict
from .satellite import SatelliteInput, SatelliteInputTypedDict
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.utils import get_discriminator
from pydantic import Discriminator, Tag
from typing import Union
from typing_extensions import Annotated, TypeAliasType


CelestialBodyInputTypedDict = TypeAliasType(
    "CelestialBodyInputTypedDict", Union[SatelliteInputTypedDict, PlanetInputTypedDict]
)
r"""A celestial body which can be either a planet or a satellite"""


CelestialBodyInput = Annotated[
    Union[
        Annotated[PlanetInput, Tag("planet")],
        Annotated[SatelliteInput, Tag("satellite")],
    ],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]
r"""A celestial body which can be either a planet or a satellite"""
