"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .planet import Planet, PlanetTypedDict
from .satellite import Satellite, SatelliteTypedDict
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.utils import get_discriminator
from pydantic import Discriminator, Tag
from typing import Union
from typing_extensions import Annotated, TypeAliasType


CelestialBodyTypedDict = TypeAliasType(
    "CelestialBodyTypedDict", Union[SatelliteTypedDict, PlanetTypedDict]
)
r"""A celestial body which can be either a planet or a satellite"""


CelestialBody = Annotated[
    Union[Annotated[Planet, Tag("planet")], Annotated[Satellite, Tag("satellite")]],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]
r"""A celestial body which can be either a planet or a satellite"""
