"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .planet import Planet, PlanetTypedDict
from typing import Union
from typing_extensions import TypeAliasType


CreatePlanetJSONResponseTypedDict = TypeAliasType(
    "CreatePlanetJSONResponseTypedDict", Union[PlanetTypedDict, bytes]
)


CreatePlanetJSONResponse = TypeAliasType(
    "CreatePlanetJSONResponse", Union[Planet, bytes]
)
