"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .user import User, UserTypedDict
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.types import BaseModel
from typing import Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


class CreateUserJSONRequestBodyTypedDict(TypedDict):
    r"""Credentials to authenticate a user"""

    email: str
    password: str
    name: NotRequired[str]


class CreateUserJSONRequestBody(BaseModel):
    r"""Credentials to authenticate a user"""

    email: str

    password: str

    name: Optional[str] = None


CreateUserJSONResponseTypedDict = TypeAliasType(
    "CreateUserJSONResponseTypedDict", Union[UserTypedDict, bytes]
)


CreateUserJSONResponse = TypeAliasType("CreateUserJSONResponse", Union[User, bytes])
