"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.types import BaseModel
from typing_extensions import TypedDict


class CredentialsTypedDict(TypedDict):
    r"""Credentials to authenticate a user"""

    email: str
    password: str


class Credentials(BaseModel):
    r"""Credentials to authenticate a user"""

    email: str

    password: str
