"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.types import BaseModel
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.utils import (
    FieldMetadata,
    PathParamMetadata,
)
import pydantic
from typing_extensions import Annotated, TypedDict


class DeletePlanetRequestTypedDict(TypedDict):
    planet_id: int
    r"""The ID of the planet to get"""


class DeletePlanetRequest(BaseModel):
    planet_id: Annotated[
        int,
        pydantic.Field(alias="planetId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The ID of the planet to get"""
