"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .planet import Planet, Planet1, Planet1TypedDict, PlanetTypedDict
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.utils import (
    FieldMetadata,
    QueryParamMetadata,
)
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class GetAllDataRequestTypedDict(TypedDict):
    limit: NotRequired[int]
    r"""The number of items to return"""
    offset: NotRequired[int]
    r"""The number of items to skip before starting to collect the result set"""


class GetAllDataRequest(BaseModel):
    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 10
    r"""The number of items to return"""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0
    r"""The number of items to skip before starting to collect the result set"""


class GetAllDataMetaTypedDict(TypedDict):
    limit: NotRequired[int]
    offset: NotRequired[int]
    total: NotRequired[int]
    next: NotRequired[Nullable[str]]


class GetAllDataMeta(BaseModel):
    limit: Optional[int] = None

    offset: Optional[int] = None

    total: Optional[int] = None

    next: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["limit", "offset", "total", "next"]
        nullable_fields = ["next"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class GetAllDataPlanetsResponseBodyTypedDict(TypedDict):
    r"""A paginated resource"""

    data: NotRequired[List[Planet1TypedDict]]
    meta: NotRequired[GetAllDataMetaTypedDict]


class GetAllDataPlanetsResponseBody(BaseModel):
    r"""A paginated resource"""

    data: Optional[List[Planet1]] = None

    meta: Optional[GetAllDataMeta] = None


class MetaTypedDict(TypedDict):
    limit: NotRequired[int]
    offset: NotRequired[int]
    total: NotRequired[int]
    next: NotRequired[Nullable[str]]


class Meta(BaseModel):
    limit: Optional[int] = None

    offset: Optional[int] = None

    total: Optional[int] = None

    next: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["limit", "offset", "total", "next"]
        nullable_fields = ["next"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class GetAllDataResponseBodyTypedDict(TypedDict):
    r"""A paginated resource"""

    data: NotRequired[List[PlanetTypedDict]]
    meta: NotRequired[MetaTypedDict]


class GetAllDataResponseBody(BaseModel):
    r"""A paginated resource"""

    data: Optional[List[Planet]] = None

    meta: Optional[Meta] = None


GetAllDataResponseTypedDict = TypeAliasType(
    "GetAllDataResponseTypedDict", Union[GetAllDataResponseBodyTypedDict, bytes]
)


GetAllDataResponse = TypeAliasType(
    "GetAllDataResponse", Union[GetAllDataResponseBody, bytes]
)
