"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .user import User, UserTypedDict
from typing import Union
from typing_extensions import TypeAliasType


GetMeResponseTypedDict = TypeAliasType(
    "GetMeResponseTypedDict", Union[UserTypedDict, bytes]
)


GetMeResponse = TypeAliasType("GetMeResponse", Union[User, bytes])
