"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .planet import Planet, PlanetTypedDict
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.types import BaseModel
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.utils import (
    FieldMetadata,
    PathParamMetadata,
)
import pydantic
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class GetPlanetRequestTypedDict(TypedDict):
    planet_id: int
    r"""The ID of the planet to get"""


class GetPlanetRequest(BaseModel):
    planet_id: Annotated[
        int,
        pydantic.Field(alias="planetId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The ID of the planet to get"""


GetPlanetResponseTypedDict = TypeAliasType(
    "GetPlanetResponseTypedDict", Union[PlanetTypedDict, bytes]
)


GetPlanetResponse = TypeAliasType("GetPlanetResponse", Union[Planet, bytes])
