"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .token import Token, TokenTypedDict
from typing import Union
from typing_extensions import TypeAliasType


GetTokenRawResponseTypedDict = TypeAliasType(
    "GetTokenRawResponseTypedDict", Union[TokenTypedDict, bytes]
)


GetTokenRawResponse = TypeAliasType("GetTokenRawResponse", Union[Token, bytes])
