"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ImageUploadedMessageTypedDict(TypedDict):
    r"""Message about an image upload"""

    message: NotRequired[str]
    image_url: NotRequired[str]
    r"""The URL where the uploaded image can be accessed"""
    uploaded_at: NotRequired[datetime]
    r"""Timestamp when the image was uploaded"""
    file_size: NotRequired[int]
    r"""Size of the uploaded image in bytes"""
    mime_type: NotRequired[str]
    r"""The content type of the uploaded image"""


class ImageUploadedMessage(BaseModel):
    r"""Message about an image upload"""

    message: Optional[str] = None

    image_url: Annotated[Optional[str], pydantic.Field(alias="imageUrl")] = None
    r"""The URL where the uploaded image can be accessed"""

    uploaded_at: Annotated[Optional[datetime], pydantic.Field(alias="uploadedAt")] = (
        None
    )
    r"""Timestamp when the image was uploaded"""

    file_size: Annotated[Optional[int], pydantic.Field(alias="fileSize")] = None
    r"""Size of the uploaded image in bytes"""

    mime_type: Annotated[Optional[str], pydantic.Field(alias="mimeType")] = None
    r"""The content type of the uploaded image"""
