"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .satellite import (
    Satellite,
    SatelliteInput,
    SatelliteInputTypedDict,
    SatelliteTypedDict,
)
from .user import User, UserTypedDict
from .user_input import UserInput, UserInputTypedDict
from datetime import datetime
from enum import Enum
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import ConfigDict, model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class Type(str, Enum):
    PLANET = "planet"
    TERRESTRIAL = "terrestrial"
    GAS_GIANT = "gas_giant"
    ICE_GIANT = "ice_giant"
    DWARF = "dwarf"
    SUPER_EARTH = "super_earth"


class TemperatureTypedDict(TypedDict):
    min: NotRequired[float]
    r"""Minimum temperature in Kelvin"""
    max: NotRequired[float]
    r"""Maximum temperature in Kelvin"""
    average: NotRequired[float]
    r"""Average temperature in Kelvin"""


class Temperature(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, float] = pydantic.Field(init=False)

    min: Optional[float] = None
    r"""Minimum temperature in Kelvin"""

    max: Optional[float] = None
    r"""Maximum temperature in Kelvin"""

    average: Optional[float] = None
    r"""Average temperature in Kelvin"""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]


class PhysicalPropertiesTypedDict(TypedDict):
    mass: NotRequired[float]
    r"""Mass in Earth masses (must be greater than 0)"""
    radius: NotRequired[float]
    r"""Radius in Earth radii (must be greater than 0)"""
    gravity: NotRequired[float]
    r"""Surface gravity in Earth g"""
    temperature: NotRequired[TemperatureTypedDict]


class PhysicalProperties(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, float] = pydantic.Field(init=False)

    mass: Optional[float] = None
    r"""Mass in Earth masses (must be greater than 0)"""

    radius: Optional[float] = None
    r"""Radius in Earth radii (must be greater than 0)"""

    gravity: Optional[float] = None
    r"""Surface gravity in Earth g"""

    temperature: Optional[Temperature] = None

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]


class AtmosphereTypedDict(TypedDict):
    compound: NotRequired[str]
    percentage: NotRequired[float]


class Atmosphere(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, str] = pydantic.Field(init=False)

    compound: Optional[str] = None

    percentage: Optional[float] = None

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]


class PlanetTypedDict(TypedDict):
    r"""A planet in the Scalar Galaxy"""

    id: int
    name: str
    type: Type
    description: NotRequired[Nullable[str]]
    habitability_index: NotRequired[float]
    r"""A score from 0 to 1 indicating potential habitability"""
    physical_properties: NotRequired[PhysicalPropertiesTypedDict]
    atmosphere: NotRequired[List[AtmosphereTypedDict]]
    r"""Atmospheric composition"""
    discovered_at: NotRequired[datetime]
    image: NotRequired[Nullable[str]]
    satellites: NotRequired[List[SatelliteTypedDict]]
    creator: NotRequired[UserTypedDict]
    r"""A user"""
    tags: NotRequired[List[str]]
    last_updated: NotRequired[datetime]
    success_callback_url: NotRequired[str]
    r"""URL which gets invoked upon a successful operation"""
    failure_callback_url: NotRequired[str]
    r"""URL which gets invoked upon a failed operation"""


class Planet(BaseModel):
    r"""A planet in the Scalar Galaxy"""

    id: int

    name: str

    type: Type

    description: OptionalNullable[str] = UNSET

    habitability_index: Annotated[
        Optional[float], pydantic.Field(alias="habitabilityIndex")
    ] = None
    r"""A score from 0 to 1 indicating potential habitability"""

    physical_properties: Annotated[
        Optional[PhysicalProperties], pydantic.Field(alias="physicalProperties")
    ] = None

    atmosphere: Optional[List[Atmosphere]] = None
    r"""Atmospheric composition"""

    discovered_at: Annotated[
        Optional[datetime], pydantic.Field(alias="discoveredAt")
    ] = None

    image: OptionalNullable[str] = UNSET

    satellites: Optional[List[Satellite]] = None

    creator: Optional[User] = None
    r"""A user"""

    tags: Optional[List[str]] = None

    last_updated: Annotated[Optional[datetime], pydantic.Field(alias="lastUpdated")] = (
        None
    )

    success_callback_url: Annotated[
        Optional[str], pydantic.Field(alias="successCallbackUrl")
    ] = None
    r"""URL which gets invoked upon a successful operation"""

    failure_callback_url: Annotated[
        Optional[str], pydantic.Field(alias="failureCallbackUrl")
    ] = None
    r"""URL which gets invoked upon a failed operation"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "description",
            "habitabilityIndex",
            "physicalProperties",
            "atmosphere",
            "discoveredAt",
            "image",
            "satellites",
            "creator",
            "tags",
            "lastUpdated",
            "successCallbackUrl",
            "failureCallbackUrl",
        ]
        nullable_fields = ["description", "image"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class Planet1TypedDict(TypedDict):
    r"""A planet in the Scalar Galaxy"""

    id: int
    name: str
    type: Type
    description: NotRequired[Nullable[str]]
    habitability_index: NotRequired[float]
    r"""A score from 0 to 1 indicating potential habitability"""
    physical_properties: NotRequired[Dict[str, float]]
    atmosphere: NotRequired[List[Dict[str, str]]]
    r"""Atmospheric composition"""
    discovered_at: NotRequired[datetime]
    image: NotRequired[Nullable[str]]
    satellites: NotRequired[List[SatelliteTypedDict]]
    creator: NotRequired[UserTypedDict]
    r"""A user"""
    tags: NotRequired[List[str]]
    last_updated: NotRequired[datetime]
    success_callback_url: NotRequired[str]
    r"""URL which gets invoked upon a successful operation"""
    failure_callback_url: NotRequired[str]
    r"""URL which gets invoked upon a failed operation"""


class Planet1(BaseModel):
    r"""A planet in the Scalar Galaxy"""

    id: int

    name: str

    type: Type

    description: OptionalNullable[str] = UNSET

    habitability_index: Optional[float] = None
    r"""A score from 0 to 1 indicating potential habitability"""

    physical_properties: Optional[Dict[str, float]] = None

    atmosphere: Optional[List[Dict[str, str]]] = None
    r"""Atmospheric composition"""

    discovered_at: Optional[datetime] = None

    image: OptionalNullable[str] = UNSET

    satellites: Optional[List[Satellite]] = None

    creator: Optional[User] = None
    r"""A user"""

    tags: Optional[List[str]] = None

    last_updated: Optional[datetime] = None

    success_callback_url: Optional[str] = None
    r"""URL which gets invoked upon a successful operation"""

    failure_callback_url: Optional[str] = None
    r"""URL which gets invoked upon a failed operation"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "description",
            "habitabilityIndex",
            "physicalProperties",
            "atmosphere",
            "discoveredAt",
            "image",
            "satellites",
            "creator",
            "tags",
            "lastUpdated",
            "successCallbackUrl",
            "failureCallbackUrl",
        ]
        nullable_fields = ["description", "image"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class PlanetInputTypedDict(TypedDict):
    r"""A planet in the Scalar Galaxy"""

    name: str
    type: Type
    description: NotRequired[Nullable[str]]
    habitability_index: NotRequired[float]
    r"""A score from 0 to 1 indicating potential habitability"""
    physical_properties: NotRequired[PhysicalPropertiesTypedDict]
    atmosphere: NotRequired[List[AtmosphereTypedDict]]
    r"""Atmospheric composition"""
    discovered_at: NotRequired[datetime]
    image: NotRequired[Nullable[str]]
    satellites: NotRequired[List[SatelliteInputTypedDict]]
    creator: NotRequired[UserInputTypedDict]
    r"""A user"""
    tags: NotRequired[List[str]]
    success_callback_url: NotRequired[str]
    r"""URL which gets invoked upon a successful operation"""
    failure_callback_url: NotRequired[str]
    r"""URL which gets invoked upon a failed operation"""


class PlanetInput(BaseModel):
    r"""A planet in the Scalar Galaxy"""

    name: str

    type: Type

    description: OptionalNullable[str] = UNSET

    habitability_index: Annotated[
        Optional[float], pydantic.Field(alias="habitabilityIndex")
    ] = None
    r"""A score from 0 to 1 indicating potential habitability"""

    physical_properties: Annotated[
        Optional[PhysicalProperties], pydantic.Field(alias="physicalProperties")
    ] = None

    atmosphere: Optional[List[Atmosphere]] = None
    r"""Atmospheric composition"""

    discovered_at: Annotated[
        Optional[datetime], pydantic.Field(alias="discoveredAt")
    ] = None

    image: OptionalNullable[str] = UNSET

    satellites: Optional[List[SatelliteInput]] = None

    creator: Optional[UserInput] = None
    r"""A user"""

    tags: Optional[List[str]] = None

    success_callback_url: Annotated[
        Optional[str], pydantic.Field(alias="successCallbackUrl")
    ] = None
    r"""URL which gets invoked upon a successful operation"""

    failure_callback_url: Annotated[
        Optional[str], pydantic.Field(alias="failureCallbackUrl")
    ] = None
    r"""URL which gets invoked upon a failed operation"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "description",
            "habitabilityIndex",
            "physicalProperties",
            "atmosphere",
            "discoveredAt",
            "image",
            "satellites",
            "creator",
            "tags",
            "successCallbackUrl",
            "failureCallbackUrl",
        ]
        nullable_fields = ["description", "image"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
