"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SatelliteType(str, Enum):
    SATELLITE = "satellite"
    MOON = "moon"
    ASTEROID = "asteroid"
    COMET = "comet"


class OrbitTypedDict(TypedDict):
    planet_id: NotRequired[int]
    r"""The ID of the planet this satellite orbits"""
    orbital_period: NotRequired[float]
    r"""Orbital period in Earth days"""
    distance: NotRequired[float]
    r"""Average distance from the planet in kilometers"""


class Orbit(BaseModel):
    planet_id: Annotated[Optional[int], pydantic.Field(alias="planetId")] = None
    r"""The ID of the planet this satellite orbits"""

    orbital_period: Annotated[
        Optional[float], pydantic.Field(alias="orbitalPeriod")
    ] = None
    r"""Orbital period in Earth days"""

    distance: Optional[float] = None
    r"""Average distance from the planet in kilometers"""


class SatelliteTypedDict(TypedDict):
    r"""Every satellite in the Scalar Galaxy"""

    name: str
    type: SatelliteType
    id: NotRequired[int]
    description: NotRequired[Nullable[str]]
    diameter: NotRequired[float]
    r"""Diameter in kilometers"""
    orbit: NotRequired[OrbitTypedDict]


class Satellite(BaseModel):
    r"""Every satellite in the Scalar Galaxy"""

    name: str

    type: SatelliteType

    id: Optional[int] = None

    description: OptionalNullable[str] = UNSET

    diameter: Optional[float] = None
    r"""Diameter in kilometers"""

    orbit: Optional[Orbit] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["id", "description", "diameter", "orbit"]
        nullable_fields = ["description"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class SatelliteInputTypedDict(TypedDict):
    r"""Every satellite in the Scalar Galaxy"""

    name: str
    type: SatelliteType
    description: NotRequired[Nullable[str]]
    diameter: NotRequired[float]
    r"""Diameter in kilometers"""
    orbit: NotRequired[OrbitTypedDict]


class SatelliteInput(BaseModel):
    r"""Every satellite in the Scalar Galaxy"""

    name: str

    type: SatelliteType

    description: OptionalNullable[str] = UNSET

    diameter: Optional[float] = None
    r"""Diameter in kilometers"""

    orbit: Optional[Orbit] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["description", "diameter", "orbit"]
        nullable_fields = ["description"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
