"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.types import BaseModel
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.utils import (
    FieldMetadata,
    SecurityMetadata,
)
from typing_extensions import Annotated, TypedDict


class SchemeOAuth2TypedDict(TypedDict):
    client_id: str
    client_secret: str
    token_url: str


class SchemeOAuth2(BaseModel):
    client_id: Annotated[
        str, FieldMetadata(security=SecurityMetadata(field_name="clientID"))
    ]

    client_secret: Annotated[
        str, FieldMetadata(security=SecurityMetadata(field_name="clientSecret"))
    ]

    token_url: str = "https://galaxy.scalar.com/oauth/token"
