"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.types import BaseModel
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.utils import (
    FieldMetadata,
    SecurityMetadata,
)
from typing_extensions import Annotated, TypedDict


class SchemeBasicAuthTypedDict(TypedDict):
    username: str
    password: str


class SchemeBasicAuth(BaseModel):
    username: Annotated[
        str, FieldMetadata(security=SecurityMetadata(field_name="username"))
    ]

    password: Annotated[
        str, FieldMetadata(security=SecurityMetadata(field_name="password"))
    ]
