"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .schemebasicauth import SchemeBasicAuth, SchemeBasicAuthTypedDict
from .schemeoauth2 import SchemeOAuth2, SchemeOAuth2TypedDict
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.types import BaseModel
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.utils import (
    FieldMetadata,
    SecurityMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SecurityTypedDict(TypedDict):
    bearer_auth: NotRequired[str]
    basic_auth: NotRequired[SchemeBasicAuthTypedDict]
    api_key_query: NotRequired[str]
    api_key_header: NotRequired[str]
    api_key_cookie: NotRequired[str]
    o_auth2: NotRequired[SchemeOAuth2TypedDict]
    open_id_connect: NotRequired[str]


class Security(BaseModel):
    bearer_auth: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ] = None

    basic_auth: Annotated[
        Optional[SchemeBasicAuth],
        FieldMetadata(
            security=SecurityMetadata(scheme=True, scheme_type="http", sub_type="basic")
        ),
    ] = None

    api_key_query: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="query",
                field_name="api_key",
            )
        ),
    ] = None

    api_key_header: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-API-Key",
            )
        ),
    ] = None

    api_key_cookie: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="cookie",
                field_name="api_key",
            )
        ),
    ] = None

    o_auth2: Annotated[
        Optional[SchemeOAuth2],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True, scheme_type="oauth2", sub_type="client_credentials"
            )
        ),
    ] = None

    open_id_connect: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True, scheme_type="openIdConnect", field_name="Authorization"
            )
        ),
    ] = None
