"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TokenTypedDict(TypedDict):
    r"""A token to authenticate a user"""

    token: NotRequired[str]


class Token(BaseModel):
    r"""A token to authenticate a user"""

    token: Optional[str] = None
