"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .planet import Planet, PlanetTypedDict
import io
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.types import BaseModel
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from typing import IO, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class UpdatePlanetRawRequestTypedDict(TypedDict):
    planet_id: int
    r"""The ID of the planet to get"""
    planet: NotRequired[Union[bytes, IO[bytes], io.BufferedReader]]
    r"""New information about the planet"""


class UpdatePlanetRawRequest(BaseModel):
    planet_id: Annotated[
        int,
        pydantic.Field(alias="planetId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The ID of the planet to get"""

    planet: Annotated[
        Optional[Union[bytes, IO[bytes], io.BufferedReader]],
        FieldMetadata(request=RequestMetadata(media_type="application/xml")),
    ] = None
    r"""New information about the planet"""


UpdatePlanetRawResponseTypedDict = TypeAliasType(
    "UpdatePlanetRawResponseTypedDict", Union[PlanetTypedDict, bytes]
)


UpdatePlanetRawResponse = TypeAliasType("UpdatePlanetRawResponse", Union[Planet, bytes])
