"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .planet import Planet, PlanetInput, PlanetInputTypedDict, PlanetTypedDict
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.types import BaseModel
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class UpdatePlanetJSONRequestTypedDict(TypedDict):
    planet_id: int
    r"""The ID of the planet to get"""
    planet: NotRequired[PlanetInputTypedDict]
    r"""New information about the planet"""


class UpdatePlanetJSONRequest(BaseModel):
    planet_id: Annotated[
        int,
        pydantic.Field(alias="planetId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The ID of the planet to get"""

    planet: Annotated[
        Optional[PlanetInput],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
    r"""New information about the planet"""


UpdatePlanetJSONResponseTypedDict = TypeAliasType(
    "UpdatePlanetJSONResponseTypedDict", Union[PlanetTypedDict, bytes]
)


UpdatePlanetJSONResponse = TypeAliasType(
    "UpdatePlanetJSONResponse", Union[Planet, bytes]
)
