"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .imageuploadedmessage import ImageUploadedMessage, ImageUploadedMessageTypedDict
import io
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.types import BaseModel
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.utils import (
    FieldMetadata,
    MultipartFormMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from typing import IO, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class ImageTypedDict(TypedDict):
    file_name: str
    content: Union[bytes, IO[bytes], io.BufferedReader]
    content_type: NotRequired[str]


class Image(BaseModel):
    file_name: Annotated[
        str, pydantic.Field(alias="fileName"), FieldMetadata(multipart=True)
    ]

    content: Annotated[
        Union[bytes, IO[bytes], io.BufferedReader],
        pydantic.Field(alias=""),
        FieldMetadata(multipart=MultipartFormMetadata(content=True)),
    ]

    content_type: Annotated[
        Optional[str],
        pydantic.Field(alias="Content-Type"),
        FieldMetadata(multipart=True),
    ] = None


class UploadImageRequestBodyTypedDict(TypedDict):
    r"""Image to upload"""

    image: NotRequired[ImageTypedDict]
    r"""The image file to upload"""


class UploadImageRequestBody(BaseModel):
    r"""Image to upload"""

    image: Annotated[
        Optional[Image], FieldMetadata(multipart=MultipartFormMetadata(file=True))
    ] = None
    r"""The image file to upload"""


class UploadImageRequestTypedDict(TypedDict):
    planet_id: int
    r"""The ID of the planet to get"""
    request_body: NotRequired[UploadImageRequestBodyTypedDict]
    r"""Image to upload"""


class UploadImageRequest(BaseModel):
    planet_id: Annotated[
        int,
        pydantic.Field(alias="planetId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The ID of the planet to get"""

    request_body: Annotated[
        Optional[UploadImageRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="multipart/form-data")),
    ] = None
    r"""Image to upload"""


UploadImageResponseTypedDict = TypeAliasType(
    "UploadImageResponseTypedDict", Union[ImageUploadedMessageTypedDict, bytes]
)


UploadImageResponse = TypeAliasType(
    "UploadImageResponse", Union[ImageUploadedMessage, bytes]
)
