"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class UserInputTypedDict(TypedDict):
    r"""A user"""

    name: NotRequired[str]


class UserInput(BaseModel):
    r"""A user"""

    name: Optional[str] = None
