"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from perianayaguyjayaselan_demo_api_scalar_galaxy_python.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class UserTypedDict(TypedDict):
    r"""A user"""

    id: NotRequired[int]
    name: NotRequired[str]


class User(BaseModel):
    r"""A user"""

    id: Optional[int] = None

    name: Optional[str] = None
